- name: My count play
  hosts: myhosts
  gather_facts: false  # Disable gathering facts for localhost

  tasks:
          - name: Count our fruit
            ansible.builtin.debug:
                msg: "{{ item }} with index {{ my_idx }}"
            loop:
                    - apple
                    - banana
                    - pear
            loop_control:
                    index_var: my_idx
